
DELETE FROM HANGMAN_MGMT_TABLE;

INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'DELL');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'DELIVER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VAKUES', 'TECHNOLOGY');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'CUSTOMER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'CLOUD');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'COMPUTER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'SERVER');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'ADVANCED');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'STORAGE');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'SOLLUTIONS');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'COMMITMENT');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'DIVERSITY');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'ENGAGEMENT');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'COMMUNITY');
INSERT INTO HANGMAN_TABLE (category, value) VALUES ('VALUES', 'MILESTONE');